### ISSUE TITLE
Why not fill all webrouter ips into tinydns

### ISSUE THREAD

**Issue by ccl0326** [laincloud/networkd#16]
In our scene, we always use internal http service with lain.local domain, but networkd support one ip only. In fact webrouter is not stateful. We just fill all ips into tinydns is fine i think.

**Comment by supermeng** [comment]
What all webrouter ips means? In our scene, we use webrouter with standby, so networkd need manage only one ip(vip or local node ip(running webrotuer) with lock).

**Comment by ccl0326** [comment]
@supermeng This can make webrouter scale out. So far we can use a SLB for load balance of webrouters. But for some internal systems,  i think if we can access them with webrouter only is better, so we use xxx.lain.local pattern for some internal systems, but there is only one ip exists in tinydns, so is there some reason for the design of webrouter with standby or we can fill all ips into tinydns?

**Comment by supermeng** [comment]
[#21](https://github.com/laincloud/networkd/pull/21)  Added NS a.ns.lain and a.ns.$domain and A Record *.lain && *.$domain in tinydns for the feature.

**Comment by ccl0326** [comment]
@supermeng Thanks~
